[IN√çCIO] 27/07/2025 14:24:31,40 
[INFO] Abrindo Chrome com WhatsApp... 
[INFO] Aguardando 20 segundos para carregamento do WhatsApp... 
[INFO] Executando enviar_todos.py... 
[*] Script iniciar...
[*] Telefone: 5548999181410
Traceback (most recent call last):
  File "C:\IMPAR\enviar_whatsapp.py", line 13, in <module>
    print(f"[*] Mensagem: {mensagem}")
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ramos\AppData\Local\Programs\Python\Python313\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f389' in position 38: character maps to <undefined>
[14:25:13] Iniciando envio pela planilha...
[14:25] Avaliando envio para M„e (5548999181410)...
     [HORA] Agora: 27/07/2025 14:25 | Agendado: 27/07/2025 14:22
[14:25] Enviando mensagem para M„e (5548999181410)...
Traceback (most recent call last):
  File "C:\IMPAR\enviar_todos.py", line 50, in main
    subprocess.run(["python", CAMINHO_SCRIPT_ENVIO, telefone, mensagem], check=True)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ramos\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 577, in run
    raise CalledProcessError(retcode, process.args,
                             output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python', 'C:/IMPAR/enviar_whatsapp.py', '5548999181410', 'Feliz anivers·rio, M„e! \U0001f389']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\IMPAR\enviar_todos.py", line 60, in <module>
    main()
    ~~~~^^
  File "C:\IMPAR\enviar_todos.py", line 53, in main
    print(f"[ERRO] Falha ao enviar para {telefone}: {str(e)}")
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ramos\AppData\Local\Programs\Python\Python313\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f389' in position 136: character maps to <undefined>
[FIM] 27/07/2025 14:25:22,20 
